package node

import (
	"encoding/json"
	"testing"
)

func TestBunSplitSpecifierSimple(t *testing.T) {
	name, version := bunSplitSpecifier("is-odd@3.0.1", "is-odd")
	if name != "is-odd" || version != "3.0.1" {
		t.Errorf("got (%q, %q), want (is-odd, 3.0.1)", name, version)
	}
}

func TestBunSplitSpecifierScoped(t *testing.T) {
	name, version := bunSplitSpecifier("@types/node@20.11.0", "@types/node")
	if name != "@types/node" || version != "20.11.0" {
		t.Errorf("got (%q, %q), want (@types/node, 20.11.0)", name, version)
	}
}

func TestBunSplitSpecifierGitHubRef(t *testing.T) {
	// A non-registry specifier still splits at the last '@' — the
	// "version" half is a raw ref, not a semver, an accepted limitation
	// (see bunSplitSpecifier's own doc comment).
	name, version := bunSplitSpecifier("uWebSockets.js@github:uNetworking/uWebSockets.js#6609a88", "uWebSocket.js")
	if name != "uWebSockets.js" || version != "github:uNetworking/uWebSockets.js#6609a88" {
		t.Errorf("got (%q, %q), want (uWebSockets.js, github:uNetworking/uWebSockets.js#6609a88)", name, version)
	}
}

func TestStripJSONCComments(t *testing.T) {
	input := `{
  // a line comment
  "a": 1, /* a block
  comment spanning lines */ "b": 2,
  "url": "http://example.com" // not a comment start inside the string above
}`
	got := stripJSONC([]byte(input))
	var out struct {
		A   int    `json:"a"`
		B   int    `json:"b"`
		URL string `json:"url"`
	}
	if err := json.Unmarshal(got, &out); err != nil {
		t.Fatalf("stripJSONC output did not parse as JSON: %v\noutput:\n%s", err, got)
	}
	if out.A != 1 || out.B != 2 || out.URL != "http://example.com" {
		t.Errorf("got %+v, want A=1 B=2 URL=http://example.com", out)
	}
}

func TestStripJSONCTrailingCommas(t *testing.T) {
	input := `{"a": 1, "b": [1, 2, 3,],}`
	got := stripJSONC([]byte(input))
	var out struct {
		A int   `json:"a"`
		B []int `json:"b"`
	}
	if err := json.Unmarshal(got, &out); err != nil {
		t.Fatalf("stripJSONC output did not parse as JSON: %v\noutput:\n%s", err, got)
	}
	if out.A != 1 || len(out.B) != 3 {
		t.Errorf("got %+v, want A=1 B=[1 2 3]", out)
	}
}

// TestResolveBunLockDirectAndTransitive is NODE-005's own acceptance
// criterion: a small real fixture with a direct and a transitive
// dependency, both resolving to correct exact versions, with scoped
// package names preserved.
func TestResolveBunLockDirectAndTransitive(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "package.json", `{"name":"demo"}`)
	writeFile(t, root, "bun.lock", `{
  // generated by bun
  "lockfileVersion": 0,
  "workspaces": {
    "": {
      "name": "demo",
      "dependencies": {
        "is-odd": "^3.0.0",
      },
    },
  },
  "packages": {
    "is-odd": ["is-odd@3.0.1", {"dependencies": {"is-number": "^6.0.0"}}, "sha512-fake=="],
    "is-number": ["is-number@6.0.0", {}, "sha512-fake=="],
    "@types/node": ["@types/node@20.11.0", {}, "sha512-fake=="],
  },
}`)

	res, err := resolveBunLock(root)
	if err != nil {
		t.Fatalf("resolveBunLock: %v", err)
	}
	byName := map[string]domainDepInfo{}
	for _, d := range res.Dependencies {
		byName[d.Dependency.Name] = domainDepInfo{version: d.Version, direct: d.Dependency.Direct}
	}
	if byName["is-odd"].version != "3.0.1" || !byName["is-odd"].direct {
		t.Errorf("is-odd = %+v, want version 3.0.1, direct true", byName["is-odd"])
	}
	if byName["is-number"].version != "6.0.0" || byName["is-number"].direct {
		t.Errorf("is-number = %+v, want version 6.0.0, direct false", byName["is-number"])
	}
	if byName["@types/node"].version != "20.11.0" {
		t.Errorf("@types/node version = %q, want 20.11.0 (scoped name preserved)", byName["@types/node"].version)
	}
	if res.Fingerprint == "" {
		t.Error("Fingerprint is empty")
	}
}

// TestResolveBunLockRealGeneratedLockfile is a genuine bun.lock —
// generated live by real Bun 1.4.2 (`bun install` against a two-line
// package.json depending on is-odd@^3.0.0) — not hand-written, matching
// yarn_test.go's own real-lockfile discipline. Confirms real Bun output
// (lockfileVersion 2, an extra "configVersion" field this ticket's
// struct doesn't declare, and each packages[key][1] being an empty
// string rather than an object) still parses correctly — resolveBunLock
// only ever reads packages[key][0], so the rest of the array's real
// shape doesn't matter.
func TestResolveBunLockRealGeneratedLockfile(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "package.json", `{"name":"demo","version":"1.0.0","dependencies":{"is-odd":"^3.0.0"}}`)
	writeFile(t, root, "bun.lock", `{
  "lockfileVersion": 2,
  "configVersion": 1,
  "workspaces": {
    "": {
      "name": "demo",
      "dependencies": {
        "is-odd": "^3.0.0",
      },
    },
  },
  "packages": {
    "is-number": ["is-number@6.0.0", "", {}, "sha512-fake=="],

    "is-odd": ["is-odd@3.0.1", "", { "dependencies": { "is-number": "^6.0.0" } }, "sha512-fake=="],
  }
}`)

	res, err := resolveBunLock(root)
	if err != nil {
		t.Fatalf("resolveBunLock: %v", err)
	}
	byName := map[string]domainDepInfo{}
	for _, d := range res.Dependencies {
		byName[d.Dependency.Name] = domainDepInfo{version: d.Version, direct: d.Dependency.Direct}
	}
	if byName["is-odd"].version != "3.0.1" || !byName["is-odd"].direct {
		t.Errorf("is-odd = %+v, want version 3.0.1, direct true", byName["is-odd"])
	}
	if byName["is-number"].version != "6.0.0" || byName["is-number"].direct {
		t.Errorf("is-number = %+v, want version 6.0.0, direct false", byName["is-number"])
	}
}

func TestResolveBunLockMissingFile(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "package.json", `{"name":"demo"}`)
	if _, err := resolveBunLock(root); err == nil {
		t.Fatal("expected an error for a missing bun.lock, got nil")
	}
}

type domainDepInfo struct {
	version string
	direct  bool
}
