package node

import (
	"testing"
)

func TestYarnDescriptorNameSimple(t *testing.T) {
	if got := yarnDescriptorName("is-odd@^3.0.0"); got != "is-odd" {
		t.Errorf("yarnDescriptorName = %q, want is-odd", got)
	}
}

func TestYarnDescriptorNameScoped(t *testing.T) {
	if got := yarnDescriptorName("@types/node@^20.0.0"); got != "@types/node" {
		t.Errorf("yarnDescriptorName = %q, want @types/node", got)
	}
}

func TestYarnBerryDescriptorNameScoped(t *testing.T) {
	if got := yarnBerryDescriptorName("@types/node@npm:^20.0.0"); got != "@types/node" {
		t.Errorf("yarnBerryDescriptorName = %q, want @types/node", got)
	}
}

func TestParseYarnClassicSimple(t *testing.T) {
	content := `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


is-odd@^3.0.0:
  version "3.0.1"
  resolved "https://registry.yarnpkg.com/is-odd/-/is-odd-3.0.1.tgz#2d8cd5da84870d21bd6d2af1e1de35c50ceb7076"
  integrity sha512-fake==
  dependencies:
    is-number "^6.0.0"

is-number@^6.0.0:
  version "6.0.0"
  resolved "https://registry.yarnpkg.com/is-number/-/is-number-6.0.0.tgz#fake"
  integrity sha512-fake==
`
	entries := parseYarnClassic([]byte(content))
	if len(entries) != 2 {
		t.Fatalf("entries = %+v, want 2", entries)
	}
	byName := map[string]string{}
	for _, e := range entries {
		byName[e.name] = e.version
	}
	if byName["is-odd"] != "3.0.1" {
		t.Errorf("is-odd version = %q, want 3.0.1", byName["is-odd"])
	}
	if byName["is-number"] != "6.0.0" {
		t.Errorf("is-number version = %q, want 6.0.0", byName["is-number"])
	}
}

func TestParseYarnClassicScopedAndMultiDescriptorBlock(t *testing.T) {
	content := `# yarn lockfile v1

"@types/node@^20.0.0", "@types/node@^20.1.0":
  version "20.11.0"
  resolved "https://registry.yarnpkg.com/@types/node/-/node-20.11.0.tgz#fake"
`
	entries := parseYarnClassic([]byte(content))
	if len(entries) != 1 || entries[0].name != "@types/node" || entries[0].version != "20.11.0" {
		t.Errorf("entries = %+v, want one @types/node@20.11.0 (multi-descriptor block collapsed to one entry)", entries)
	}
}

func TestParseYarnBerrySkipsWorkspaceLinks(t *testing.T) {
	content := `__metadata:
  version: 6
  cacheKey: 8

"demo@workspace:.":
  version: 0.0.0-use.local
  resolution: "demo@workspace:."
  dependencies:
    is-odd: "npm:^3.0.0"
  languageName: unknown
  linkType: soft

"is-odd@npm:^3.0.0":
  version: 3.0.1
  resolution: "is-odd@npm:3.0.1"
  dependencies:
    is-number: "npm:^6.0.0"
  languageName: node
  linkType: hard

"is-number@npm:^6.0.0":
  version: 6.0.0
  resolution: "is-number@npm:6.0.0"
  languageName: node
  linkType: hard
`
	entries, err := parseYarnBerry([]byte(content))
	if err != nil {
		t.Fatalf("parseYarnBerry: %v", err)
	}
	if len(entries) != 2 {
		t.Fatalf("entries = %+v, want 2 (the workspace's own soft-linked self-entry excluded)", entries)
	}
	byName := map[string]string{}
	for _, e := range entries {
		byName[e.name] = e.version
	}
	if byName["is-odd"] != "3.0.1" || byName["is-number"] != "6.0.0" {
		t.Errorf("entries = %+v, want is-odd@3.0.1 and is-number@6.0.0", entries)
	}
	if _, ok := byName["demo"]; ok {
		t.Error("the workspace's own linkType:soft self-entry leaked into the results")
	}
}

// TestResolveYarnLockClassicDirectAndTransitive is NODE-004's own
// acceptance criterion: a real Yarn Classic fixture resolving a direct
// and a transitive dependency to correct exact versions.
func TestResolveYarnLockClassicDirectAndTransitive(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "package.json", `{"name":"demo","dependencies":{"is-odd":"^3.0.0"}}`)
	writeFile(t, root, "yarn.lock", `# yarn lockfile v1

is-odd@^3.0.0:
  version "3.0.1"
  resolved "https://registry.yarnpkg.com/is-odd/-/is-odd-3.0.1.tgz#fake"
  dependencies:
    is-number "^6.0.0"

is-number@^6.0.0:
  version "6.0.0"
  resolved "https://registry.yarnpkg.com/is-number/-/is-number-6.0.0.tgz#fake"
`)

	res, err := resolveYarnLock(root)
	if err != nil {
		t.Fatalf("resolveYarnLock: %v", err)
	}
	byName := map[string]bool{}
	for _, d := range res.Dependencies {
		byName[d.Dependency.Name] = d.Dependency.Direct
		if d.Dependency.Name == "is-odd" && d.Version != "3.0.1" {
			t.Errorf("is-odd version = %q, want 3.0.1", d.Version)
		}
		if d.Dependency.Name == "is-number" && d.Version != "6.0.0" {
			t.Errorf("is-number version = %q, want 6.0.0", d.Version)
		}
	}
	if !byName["is-odd"] {
		t.Error("is-odd: Direct = false, want true (declared in package.json)")
	}
	if byName["is-number"] {
		t.Error("is-number: Direct = true, want false (transitive only)")
	}
	if res.Fingerprint == "" {
		t.Error("Fingerprint is empty")
	}
}

// TestResolveYarnLockBerryWorkspaceMemberMarkedLocal is NODE-004's other
// acceptance criterion: a Yarn Berry fixture with a workspace member,
// whose own workspace: self-entry must never appear as a resolved
// dependency version.
func TestResolveYarnLockBerryWorkspaceMemberMarkedLocal(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "package.json", `{"name":"demo","dependencies":{"is-odd":"^3.0.0"}}`)
	writeFile(t, root, "yarn.lock", `__metadata:
  version: 6
  cacheKey: 8

"demo@workspace:.":
  version: 0.0.0-use.local
  resolution: "demo@workspace:."
  dependencies:
    is-odd: "npm:^3.0.0"
  languageName: unknown
  linkType: soft

"is-odd@npm:^3.0.0":
  version: 3.0.1
  resolution: "is-odd@npm:3.0.1"
  languageName: node
  linkType: hard
`)

	res, err := resolveYarnLock(root)
	if err != nil {
		t.Fatalf("resolveYarnLock: %v", err)
	}
	if len(res.Dependencies) != 1 || res.Dependencies[0].Dependency.Name != "is-odd" || res.Dependencies[0].Version != "3.0.1" {
		t.Errorf("Dependencies = %+v, want just is-odd@3.0.1 (the workspace's own local self-entry must never appear)", res.Dependencies)
	}
	if !res.Dependencies[0].Dependency.Direct {
		t.Error("is-odd: Direct = false, want true")
	}
}

func TestReadPackageJSONDirectNames(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "package.json", `{"name":"demo","dependencies":{"is-odd":"^3.0.0"},"devDependencies":{"vitest":"^1.0.0"}}`)

	direct, err := readPackageJSONDirectNames(root)
	if err != nil {
		t.Fatalf("readPackageJSONDirectNames: %v", err)
	}
	if !direct["is-odd"] || !direct["vitest"] {
		t.Errorf("direct = %+v, want is-odd and vitest both true", direct)
	}
	if direct["is-number"] {
		t.Error("is-number unexpectedly marked direct")
	}
}

// TestParseYarnClassicRealGeneratedLockfile is a genuine
// yarn.lock — generated live by real Yarn 1.22.22 (via corepack,
// `yarn install --ignore-scripts` against a two-line package.json
// depending on is-odd@^3.0.0) — not hand-written, unlike this file's
// other fixtures. Catches anything a hand-crafted fixture might
// accidentally get "right" by construction.
func TestParseYarnClassicRealGeneratedLockfile(t *testing.T) {
	const realYarnLock = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


is-number@^6.0.0:
  version "6.0.0"
  resolved "https://registry.yarnpkg.com/is-number/-/is-number-6.0.0.tgz#e6d15ad31fc262887cccf217ae5f9316f81b1995"
  integrity sha512-Wu1VHeILBK8KAWJUAiSZQX94GmOE45Rg6/538fKwiloUu21KncEkYGPqob2oSZ5mUT73vLGrHQjKw3KMPwfDzg==

is-odd@^3.0.0:
  version "3.0.1"
  resolved "https://registry.yarnpkg.com/is-odd/-/is-odd-3.0.1.tgz#65101baf3727d728b66fa62f50cda7f2d3989601"
  integrity sha512-CQpnWPrDwmP1+SMHXZhtLtJv90yiyVfluGsX5iNCVkrhQtU3TQHsUWPG9wkdk9Lgd5yNpAg9jQEo90CBaXgWMA==
  dependencies:
    is-number "^6.0.0"
`
	entries := parseYarnClassic([]byte(realYarnLock))
	if len(entries) != 2 {
		t.Fatalf("entries = %+v, want 2", entries)
	}
	byName := map[string]string{}
	for _, e := range entries {
		byName[e.name] = e.version
	}
	if byName["is-odd"] != "3.0.1" {
		t.Errorf("is-odd version = %q, want 3.0.1", byName["is-odd"])
	}
	if byName["is-number"] != "6.0.0" {
		t.Errorf("is-number version = %q, want 6.0.0", byName["is-number"])
	}
}

// TestParseYarnBerryRealGeneratedLockfile is a genuine yarn.lock —
// generated live by real Yarn 4.5.0 (via corepack, `yarn install`
// against a two-line package.json depending on is-odd@^3.0.0) — not
// hand-written, matching TestParseYarnClassicRealGeneratedLockfile's
// own discipline for the Classic format.
func TestParseYarnBerryRealGeneratedLockfile(t *testing.T) {
	const realYarnBerryLock = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"demo@workspace:.":
  version: 0.0.0-use.local
  resolution: "demo@workspace:."
  dependencies:
    is-odd: "npm:^3.0.0"
  languageName: unknown
  linkType: soft

"is-number@npm:^6.0.0":
  version: 6.0.0
  resolution: "is-number@npm:6.0.0"
  checksum: 10c0/5da4c68401529675c575878d2760d66f18eaef4b014858577f6003daf66488d7fe4eae684b1e8574e3fa1bb447c6c6c56b8491d2b4b3239da2d32e5f6f218008
  languageName: node
  linkType: hard

"is-odd@npm:^3.0.0":
  version: 3.0.1
  resolution: "is-odd@npm:3.0.1"
  dependencies:
    is-number: "npm:^6.0.0"
  checksum: 10c0/89ee2e353c5a3f3bd400c79db1c307a5b3506198ee8169d521e533a9b1d8a08fc95f21a919c084e98845b4286d7ffe309778da03744dfe66c3c1763ab1a030c6
  languageName: node
  linkType: hard
`
	entries, err := parseYarnBerry([]byte(realYarnBerryLock))
	if err != nil {
		t.Fatalf("parseYarnBerry: %v", err)
	}
	if len(entries) != 2 {
		t.Fatalf("entries = %+v, want 2 (the workspace's own soft-linked self-entry excluded)", entries)
	}
	byName := map[string]string{}
	for _, e := range entries {
		byName[e.name] = e.version
	}
	if byName["is-odd"] != "3.0.1" || byName["is-number"] != "6.0.0" {
		t.Errorf("entries = %+v, want is-odd@3.0.1 and is-number@6.0.0", entries)
	}
	if _, ok := byName["demo"]; ok {
		t.Error("the workspace's own linkType:soft self-entry leaked into the results")
	}
}

func TestResolveYarnLockMissingFile(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "package.json", `{"name":"demo"}`)
	if _, err := resolveYarnLock(root); err == nil {
		t.Fatal("expected an error for a missing yarn.lock, got nil")
	}
}
